eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-server
server:
  port: 8761